// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzxlphfkogshogxgrefu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6eGxwaGZrb2dzaG9neGdyZWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNDQ1NzEsImV4cCI6MjA1MDkyMDU3MX0.GvdNTFRSXDr2lHNptC21hTftoRAFXFEm7xzVpA_eHpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);